name: Python CI

on:
  push:
    branches: [ "master" , "main" ]
  pull_request:
    branches: [ "master" , "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.14' 
      - name: Run tests with pytest
        run: python -m unittest discover -s . -p "*test*.py"
